import type { AnalysisResult, ClassifiedReview, EngineeringRule, ReviewRecord, RuleCategory, RuleEvidence, RuleStatus } from '@reviewdna/schema';
const NOISE=/^(lgtm|looks good|nice|thanks|thank you|done|fixed|nit:?\s*$|👍|✅)[.!\s]*$/i;
const QUESTION_ONLY=/^(why|what|how|could|can|should|is|are|do|does|did)\b.*\?$/i;
const GENERALIZERS=/\b(always|never|should|must|prefer|avoid|require|required|do not|don't|needs? to|belongs? in|use|instead of)\b/i;
const ONE_OFF=/\b(temporary|for now|this migration|this one|one[- ]off|hotfix|until we)\b/i;
const CATEGORY_PATTERNS:Array<[RuleCategory,RegExp]>=[['security',/\b(secret|token|password|auth|sanitize|xss|csrf|permission|security|encrypt|credential)\b/i],['testing',/\b(test|spec|coverage|regression|mock|fixture|assert)\b/i],['performance',/\b(performance|n\+1|cache|memo|latency|slow|query count|allocation)\b/i],['api-design',/\b(api|endpoint|status code|404|payload|request|response|schema|validation)\b/i],['architecture',/\b(controller|service layer|repository layer|architecture|domain|module|boundary|dependency injection)\b/i],['error-handling',/\b(error|exception|throw|catch|retry|fallback|swallow)\b/i],['documentation',/\b(document|docs|readme|comment|jsdoc|docstring)\b/i],['dependency',/\b(dependency|package|library|npm|module|axios|fetch)\b/i],['naming',/\b(name|naming|rename|camelcase|snake_case|suffix|prefix)\b/i],['maintainability',/\b(refactor|duplicate|reuse|extract|helper|maintain|complexity)\b/i],['style',/\b(format|style|indent|semicolon|quote|prettier|eslint)\b/i]];
export function normalizeReview(input:ReviewRecord):ReviewRecord{return {...input,body:input.body.replace(/\r\n/g,'\n').replace(/\s+/g,' ').trim()};}
export function classifyReview(input:ReviewRecord):ClassifiedReview{const review=normalizeReview(input);const noise=review.body.length<4||NOISE.test(review.body);const oneOff=ONE_OFF.test(review.body);const question=QUESTION_ONLY.test(review.body);const generalizable=!noise&&!oneOff&&(GENERALIZERS.test(review.body)||review.body.length>55)&&!question;const actionable=generalizable||/\b(move|add|remove|replace|rename|validate|extract|handle|return|use|avoid|don't|do not)\b/i.test(review.body);const category=CATEGORY_PATTERNS.find(([,p])=>p.test(review.body))?.[0]??'general';const confidence=Math.max(.05,Math.min(.99,(noise?.05:.35)+(actionable?.25:0)+(generalizable?.25:0)-(oneOff?.35:0)-(question?.2:0)));return {...review,actionable,generalizable,category,noise,oneOff,confidence};}
function imperativeRule(text:string){let t=text.trim().replace(/^[-*]\s*/,'').replace(/^(nit|suggestion|suggestion:|please)[:\s-]*/i,'');t=t.replace(/\bI (?:think|would|prefer|suggest)\b[:,]?\s*/i,'').replace(/\bcan we\b/i,'Prefer to').replace(/\bcould you\b/i,'');const ss=t.split(/(?<=[.!?])\s+/).filter(Boolean);t=ss.find(s=>GENERALIZERS.test(s))??ss[0]??t;t=t.replace(/\?$/,'.').trim();if(!/[.!]$/.test(t))t+='.';return t.charAt(0).toUpperCase()+t.slice(1);}
function tokens(text:string){const stop=new Set(['the','a','an','to','of','in','on','for','this','that','is','are','be','we','you','it','and','or','with','should','must','always','never','please','use','using','instead','like']);const aliases:Record<string,string>={db:'database',query:'database',queries:'database',validated:'validate',validation:'validate',validating:'validate',repositories:'repository',controllers:'controller',payloads:'payload',endpoints:'endpoint',services:'service',tests:'test',changes:'change'};const raw=text.toLowerCase().replace(/[^a-z0-9_+-]+/g,' ').split(/\s+/).filter(Boolean);const normalized=raw.map(x=>aliases[x]??(x.length>5&&x.endsWith('s')&&!x.endsWith('ss')?x.slice(0,-1):x));return new Set(normalized.filter(x=>x.length>2&&!stop.has(x)));}
function similarity(a:string,b:string){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let i=0;for(const t of A)if(B.has(t))i++;return i/(A.size+B.size-i);}
function scopeOf(rs:ClassifiedReview[]){const dirs=rs.map(r=>r.path).filter((x):x is string=>Boolean(x)).map(p=>p.includes('/')?p.split('/')[0]+'/**':p);const counts=new Map<string,number>();for(const d of dirs)counts.set(d,(counts.get(d)??0)+1);const min=Math.max(2,Math.ceil(rs.length*.6));const scopes=[...counts].filter(([,n])=>n>=min).map(([d])=>d);return scopes.length?scopes:['repository'];}
function scoreCluster(c:ClassifiedReview[],now=new Date()):EngineeringRule['scoreBreakdown']{const evidence=c.length,reviewers=new Set(c.map(r=>r.reviewer)).size,dates=c.map(r=>new Date(r.createdAt).getTime()).sort((a,b)=>a-b),newest=dates.at(-1)??now.getTime(),oldest=dates[0]??newest,age=Math.max(0,(now.getTime()-newest)/86400000),span=Math.max(0,(newest-oldest)/86400000),accepted=c.filter(r=>r.accepted||r.resolved).length;const frequency=Math.min(30,evidence*4),reviewerDiversity=Math.min(20,reviewers*4),recency=Math.max(0,Math.round(20-age/30)),acceptedEvidence=evidence?Math.round(20*accepted/evidence):0,persistence=Math.min(10,Math.round(span/30)),conflictPenalty=0,total=Math.max(0,Math.min(100,frequency+reviewerDiversity+recency+acceptedEvidence+persistence));return {frequency,reviewerDiversity,recency,acceptedEvidence,persistence,conflictPenalty,total};}
function statusFrom(score:number,lastSeen:string,firstSeen:string):RuleStatus{const age=(Date.now()-new Date(lastSeen).getTime())/86400000;if(age>365)return'stale';const span=(new Date(lastSeen).getTime()-new Date(firstSeen).getTime())/86400000;if(score>=85)return'strong';if(score>=65)return'established';if(span<60)return'emerging';return'established';}
function evidenceOf(r:ClassifiedReview):RuleEvidence{const e:RuleEvidence={id:r.id,prNumber:r.prNumber,reviewer:r.reviewer,createdAt:r.createdAt,url:r.url,body:r.body};if(r.path!==undefined)e.path=r.path;if(r.accepted!==undefined)e.accepted=r.accepted;if(r.resolved!==undefined)e.resolved=r.resolved;return e;}
export function discoverRules(records:ReviewRecord[],repository:string,source:'github'|'fixture'='github'):AnalysisResult{const classified=records.map(classifyReview),candidates=classified.filter(r=>r.actionable&&r.generalizable&&!r.noise&&!r.oneOff),rejected=classified.filter(r=>!candidates.includes(r)).map(r=>({id:r.id,body:r.body,reason:r.noise?'noise':r.oneOff?'one-off':!r.actionable?'not-actionable':'not-generalizable'})),clusters:ClassifiedReview[][]=[];for(const review of candidates){const target=clusters.find(c=>c[0]&&c[0].category===review.category&&similarity(c[0].body,review.body)>=.16);if(target)target.push(review);else clusters.push([review]);}const rules=clusters.map((cluster,index)=>{const sorted=[...cluster].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),score=scoreCluster(cluster),firstSeen=sorted[0]?.createdAt??new Date().toISOString(),lastSeen=sorted.at(-1)?.createdAt??firstSeen;return {id:`RULE-${String(index+1).padStart(4,'0')}`,text:imperativeRule([...cluster].sort((a,b)=>b.body.length-a.body.length)[0]?.body??''),category:cluster[0]?.category??'general',status:statusFrom(score.total,lastSeen,firstSeen),confidence:score.total,evidenceCount:cluster.length,reviewerCount:new Set(cluster.map(r=>r.reviewer)).size,firstSeen,lastSeen,scope:scopeOf(cluster),documented:false,conflictingRuleIds:[],evidence:sorted.map(evidenceOf),scoreBreakdown:score} satisfies EngineeringRule;}).sort((a,b)=>b.confidence-a.confidence);detectConflicts(rules);const prs=new Set(records.map(r=>r.prNumber)),reviewers=new Set(records.map(r=>r.reviewer)),categoryCounts:Record<string,number>={};for(const r of rules)categoryCounts[r.category]=(categoryCounts[r.category]??0)+1;return {schemaVersion:'1.0',summary:{repository,generatedAt:new Date().toISOString(),reviewsAnalyzed:records.length,pullRequests:prs.size,reviewers:reviewers.size,rules:rules.length,highConfidenceRules:rules.filter(r=>r.confidence>=80).length,emergingRules:rules.filter(r=>r.status==='emerging').length,conflictingRules:rules.filter(r=>r.conflictingRuleIds.length).length,staleRules:rules.filter(r=>r.status==='stale').length,undocumentedRules:rules.filter(r=>!r.documented).length,categoryCounts},rules,rejected,metadata:{engineVersion:'0.1.0',mode:'deterministic',source}};}
function oppositeSignal(text:string){return {negative:/\b(avoid|never|do not|don't|remove|stop|instead of)\b/i.test(text)};}
export function detectConflicts(rules:EngineeringRule[]){for(let i=0;i<rules.length;i++)for(let j=i+1;j<rules.length;j++){const a=rules[i],b=rules[j];if(!a||!b||a.category!==b.category)continue;const sa=oppositeSignal(a.text),sb=oppositeSignal(b.text);if(sa.negative!==sb.negative&&similarity(a.text,b.text)>=.22){a.conflictingRuleIds.push(b.id);b.conflictingRuleIds.push(a.id);a.status='disputed';b.status='disputed';for(const r of [a,b]){r.scoreBreakdown.conflictPenalty=15;r.scoreBreakdown.total=Math.max(0,r.scoreBreakdown.total-15);r.confidence=r.scoreBreakdown.total;}}}}
