import type { RuleCategory } from '@reviewdna/schema';

export const NOISE = /^(lgtm|looks good|nice|thanks|thank you|done|fixed|nit:?\s*$|👍|✅)[.!\s]*$/i;
export const QUESTION_ONLY = /^(why|what|how|could|can|should|is|are|do|does|did)\b.*\?$/i;
export const GENERALIZERS = /\b(always|never|should|must|prefer|avoid|require|required|do not|don't|needs? to|belongs? in|use|instead of)\b/i;
export const ONE_OFF = /\b(temporary|for now|this migration|this one|one[- ]off|hotfix|until we)\b/i;
export const BOT_REVIEWER = /(?:\[bot\]$|^dependabot$|^renovate(?:\[bot\])?$|^github-actions(?:\[bot\])?$)/i;
export const CATEGORY_PATTERNS:Array<[RuleCategory,RegExp]>=[['security',/\b(secrets?|tokens?|passwords?|auth(?:entication|orization)?|sanitize|xss|csrf|permissions?|security|encrypt|credentials?)\b/i],['testing',/\b(tests?|specs?|coverage|regression|mocks?|fixtures?|assert(?:ion|ions)?)\b/i],['performance',/\b(performance|n\+1|cache|memo|latency|slow|query count|allocation)\b/i],['naming',/\b(name|naming|rename|camelcase|snake_case|suffix|prefix)\b/i],['error-handling',/\b(errors?|exceptions?|throw|rethrow|catch|retry|fallback|swallow)\b/i],['documentation',/\b(document|documentation|docs|readme|comment|jsdoc|docstring)\b/i],['dependency',/\b(dependency|package|library|npm|module|axios|fetch)\b/i],['maintainability',/\b(refactor|duplicate|reuse|reusable|extract|helper|maintain|complexity)\b/i],['style',/\b(format|formatting|style|indent|semicolon|quote|prettier|eslint)\b/i],['api-design',/\b(apis?|endpoints?|status code|404|payloads?|requests?|responses?|schema|validation)\b/i],['architecture',/\b(controllers?|service layer|repository layer|architecture|domain|module|boundary|dependency injection)\b/i]];
export function tokens(text:string):Set<string>{const stop=new Set(['the','a','an','to','of','in','on','for','this','that','is','are','be','we','you','it','and','or','with','should','must','always','never','please','use','using','instead','like']),aliases:Record<string,string>={db:'database',query:'database',queries:'database',validated:'validate',validation:'validate',validating:'validate',repositories:'repository',controllers:'controller',payloads:'payload',endpoints:'endpoint',services:'service',tests:'test',changes:'change'},raw=text.toLowerCase().replace(/[^a-z0-9_+-]+/g,' ').split(/\s+/).filter(Boolean),normalized=raw.map(x=>aliases[x]??(x.length>5&&x.endsWith('s')&&!x.endsWith('ss')?x.slice(0,-1):x));return new Set(normalized.filter(x=>x.length>2&&!stop.has(x)));}
export function similarity(a:string,b:string):number{const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let intersection=0;for(const t of A)if(B.has(t))intersection++;return intersection/(A.size+B.size-intersection);}
export function negativePolarity(text:string):boolean{return /\b(avoid|never|do not|don't|must not|should not|remove|stop|instead of|not)\b/i.test(text);}
export function conceptSimilarity(a:string,b:string):number{const strip=(x:string)=>x.replace(/\b(avoid|never|do not|don't|must not|should not|remove|stop|instead of|not)\b/gi,' ');return similarity(strip(a),strip(b));}
