import type { AnalysisResult } from '@reviewdna/schema';
function esc(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]??c));}
export function renderHtml(result:AnalysisResult):string{
  const data=JSON.stringify(result).replace(/</g,'\\u003c');
  const cats=Object.entries(result.summary.categoryCounts).sort((a,b)=>b[1]-a[1]);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ReviewDNA · ${esc(result.summary.repository)}</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui;background:#0b0d12;color:#eef1f6}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1200px;margin:auto;padding:32px}.hero{display:flex;justify-content:space-between;gap:24px;align-items:end}.brand{font-size:13px;letter-spacing:.16em;text-transform:uppercase;color:#9aa4b5}.title{font-size:42px;margin:8px 0}.muted{color:#98a2b3}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:28px 0}.card{background:#131722;border:1px solid #252b38;border-radius:16px;padding:18px}.metric{font-size:30px;font-weight:750}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0}input,select{background:#10141d;color:#eef1f6;border:1px solid #303746;border-radius:10px;padding:11px 13px}.rule{background:#11151f;border:1px solid #252b38;border-radius:16px;padding:18px;margin:12px 0}.row{display:flex;justify-content:space-between;gap:20px;align-items:start}.badge{padding:5px 9px;border-radius:999px;background:#202738;font-size:12px}.score{font-size:22px;font-weight:750}.evidence{display:none;margin-top:14px;border-top:1px solid #252b38;padding-top:12px}.evidence.open{display:block}.ev{padding:10px 0;border-bottom:1px solid #202532}.ev a{color:#9cc2ff}.bar{height:8px;background:#262d39;border-radius:9px;overflow:hidden}.bar>i{display:block;height:100%;background:linear-gradient(90deg,#7c5cff,#42d3ff)}button{background:#202738;color:#fff;border:0;border-radius:9px;padding:8px 10px;cursor:pointer}@media(max-width:700px){.title{font-size:30px}.hero{display:block}}
</style></head><body><main class="wrap"><section class="hero"><div><div class="brand">ReviewDNA · Engineering Knowledge Mining</div><h1 class="title">${esc(result.summary.repository)}</h1><div class="muted">Evidence-backed conventions inferred from public code-review history. Not official repository policy.</div></div><div class="muted">${new Date(result.summary.generatedAt).toLocaleString()}</div></section>
<section class="grid">${[['Reviews',result.summary.reviewsAnalyzed],['Pull Requests',result.summary.pullRequests],['Reviewers',result.summary.reviewers],['Rules',result.summary.rules],['High confidence',result.summary.highConfidenceRules],['Conflicts',result.summary.conflictingRules],['Stale',result.summary.staleRules],['Undocumented',result.summary.undocumentedRules],['Docs coverage',result.summary.documentationCoverage+'%'],['Docs drift',result.summary.documentationDrift]].map(([k,v])=>`<div class="card"><div class="muted">${k}</div><div class="metric">${v}</div></div>`).join('')}</section>
<section class="card"><div class="row"><div><strong>Engineering DNA</strong><div class="muted">Rule distribution by category</div></div></div>${cats.map(([c,n])=>`<div style="margin-top:12px"><div class="row"><span>${esc(c)}</span><span>${n}</span></div><div class="bar"><i style="width:${Math.min(100,n/Math.max(1,result.summary.rules)*100)}%"></i></div></div>`).join('')}</section>
<div class="toolbar"><input id="q" placeholder="Search rules or evidence…"><select id="category"><option value="">All categories</option>${cats.map(([c])=>`<option>${esc(c)}</option>`).join('')}</select><select id="status"><option value="">All statuses</option>${['strong','established','emerging','disputed','stale'].map(s=>`<option>${s}</option>`).join('')}</select></div><div id="rules"></div></main>
<script>const DATA=${data};const root=document.getElementById('rules');const q=document.getElementById('q'),cat=document.getElementById('category'),status=document.getElementById('status');function e(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function render(){const term=q.value.toLowerCase();const list=DATA.rules.filter(r=>(!cat.value||r.category===cat.value)&&(!status.value||r.status===status.value)&&(!term||r.text.toLowerCase().includes(term)||r.evidence.some(x=>x.body.toLowerCase().includes(term))));root.innerHTML=list.map(r=>'<article class="rule"><div class="row"><div><div><span class="badge">'+e(r.category)+'</span> <span class="badge">'+e(r.status)+'</span>'+(r.humanDecision?' <span class="badge">human: '+e(r.humanDecision.action)+'</span>':'')+'</div><h3>'+e(r.text)+'</h3><div class="muted">'+r.evidenceCount+' evidence · '+r.reviewerCount+' reviewers · '+e(r.scope.join(', '))+' · '+e(r.fingerprint)+(r.documented?' · documented in '+e(r.documentedBy.join(', ')):' · undocumented')+(r.documentationConflicts.length?' · ⚠ docs conflict: '+e(r.documentationConflicts.join(', ')):'')+'</div></div><div class="score">'+r.confidence+'%</div></div><div style="margin-top:12px"><button onclick="this.parentElement.nextElementSibling.classList.toggle(\'open\')">View evidence</button></div><div class="evidence">'+r.evidence.map(x=>'<div class="ev"><a target="_blank" rel="noreferrer" href="'+e(x.url)+'">PR #'+x.prNumber+' · '+e(x.reviewer)+'</a><div>'+e(x.body)+'</div><div class="muted">'+e(x.createdAt)+(x.path?' · '+e(x.path):'')+'</div></div>').join('')+'</div></article>').join('')||'<div class="card">No matching rules.</div>'}q.oninput=cat.onchange=status.onchange=render;render();</script></body></html>`;
}
