import type { AnalysisResult, EngineeringRule } from '@reviewdna/schema';
function accepted(result:AnalysisResult){return result.rules.filter(r=>r.confidence>=65&&r.status!=='stale'&&r.status!=='disputed'&&r.documentationConflicts.length===0);}
function group(rules:EngineeringRule[]){const m=new Map<string,EngineeringRule[]>();for(const r of rules){const k=r.scope.join(', ');m.set(k,[...(m.get(k)??[]),r]);}return m;}
export function exportAgents(result:AnalysisResult):string{
  let out=`# AGENTS.md — generated suggestion by ReviewDNA\n\n> Evidence-backed suggestions from ${result.summary.reviewsAnalyzed} historical review records. Review before adopting.\n\n`;
  for(const [scope,rules] of group(accepted(result))){out+=`## Scope: ${scope}\n\n`;for(const r of rules)out+=`- ${r.text} _(${r.confidence}% confidence, ${r.evidenceCount} evidence)_\n`;out+='\n';}return out;
}
export function exportClaude(result:AnalysisResult):string{return `# CLAUDE.md — ReviewDNA suggestions\n\n${accepted(result).map(r=>`- ${r.text}`).join('\n')}\n`;}
export function exportCursor(result:AnalysisResult):string{return `---\ndescription: Evidence-backed repository conventions generated by ReviewDNA\nalwaysApply: true\n---\n\n${accepted(result).map(r=>`- ${r.text}`).join('\n')}\n`;}
export function exportMarkdown(result:AnalysisResult):string{
  let out=`# ${result.summary.repository} Engineering DNA\n\nGenerated ${result.summary.generatedAt}.\n\n| Rule | Confidence | Evidence | Status |\n|---|---:|---:|---|\n`;
  for(const r of result.rules)out+=`| ${r.text.replace(/\|/g,'\\|')} | ${r.confidence}% | ${r.evidenceCount} | ${r.status} |\n`;return out;
}

export function exportDeltaMarkdown(delta:{newRules:EngineeringRule[];removedRules:EngineeringRule[];strengthened:Array<{before:EngineeringRule;after:EngineeringRule}>;weakened:Array<{before:EngineeringRule;after:EngineeringRule}>;changed?:Array<{before:EngineeringRule;after:EngineeringRule;changes:string[]}>;documentationChanges?:Array<{before:EngineeringRule;after:EngineeringRule;changes:string[]}>},repository:string):string{
  const changed=delta.changed??[],documentationChanges=delta.documentationChanges??[];
  let out=`# ${repository} ReviewDNA change report\n\n`;
  out+=`- New rules: ${delta.newRules.length}\n- Removed rules: ${delta.removedRules.length}\n- Strengthened: ${delta.strengthened.length}\n- Weakened: ${delta.weakened.length}\n- Changed: ${changed.length}\n- Documentation changes: ${documentationChanges.length}\n\n`;
  const section=(title:string,lines:string[])=>{if(lines.length)out+=`## ${title}\n\n${lines.map(x=>`- ${x}`).join('\n')}\n\n`;};
  section('New conventions',delta.newRules.map(r=>`[${r.category}] ${r.text} (${r.confidence}%)`));
  section('Removed conventions',delta.removedRules.map(r=>`[${r.category}] ${r.text}`));
  section('Strengthened',delta.strengthened.map(p=>`${p.after.text} (${p.before.confidence}% → ${p.after.confidence}%)`));
  section('Weakened',delta.weakened.map(p=>`${p.after.text} (${p.before.confidence}% → ${p.after.confidence}%)`));
  section('Convention changes',changed.map(p=>`${p.after.text} — ${p.changes.join(', ')}`));
  section('Documentation changes',documentationChanges.map(p=>`${p.after.text} — ${p.changes.join(', ')}`));
  return out;
}
