import type { AnalysisResult, EngineeringRule, KnowledgeProposalManifest } from '@reviewdna/schema';

export function selectPolicyRules(result:AnalysisResult){
  return result.rules.filter(r=>r.humanDecision?.action!=='ignore'&&((r.humanDecision?.action==='promote'||r.humanDecision?.action==='override')||(r.confidence>=65&&r.status!=='stale'&&r.status!=='disputed'&&r.documentationConflicts.length===0)));
}
function group(rules:EngineeringRule[]){const m=new Map<string,EngineeringRule[]>();for(const r of rules){const k=r.scope.join(', ');m.set(k,[...(m.get(k)??[]),r]);}return m;}

export function exportAgents(result:AnalysisResult):string{
  let out=`# AGENTS.md — generated suggestion by ReviewDNA\n\n> Evidence-backed suggestions from ${result.summary.reviewsAnalyzed} historical review records. Review before adopting.\n\n`;
  for(const [scope,rules] of group(selectPolicyRules(result))){out+=`## Scope: ${scope}\n\n`;for(const r of rules)out+=`- ${r.text} _(${r.confidence}% confidence, ${r.evidenceCount} evidence)_\n`;out+='\n';}return out;
}
export function exportClaude(result:AnalysisResult):string{return `# CLAUDE.md — ReviewDNA suggestions\n\n${selectPolicyRules(result).map(r=>`- ${r.text}`).join('\n')}\n`;}
export function exportCursor(result:AnalysisResult):string{return `---\ndescription: Evidence-backed repository conventions generated by ReviewDNA\nalwaysApply: true\n---\n\n${selectPolicyRules(result).map(r=>`- ${r.text}`).join('\n')}\n`;}
export function exportMarkdown(result:AnalysisResult):string{
  let out=`# ${result.summary.repository} Engineering DNA\n\nGenerated ${result.summary.generatedAt}.\n\n| Rule | Confidence | Evidence | Status | Decision |\n|---|---:|---:|---|---|\n`;
  for(const r of result.rules)out+=`| ${r.text.replace(/\|/g,'\\|')} | ${r.confidence}% | ${r.evidenceCount} | ${r.status} | ${r.humanDecision?.action??'—'} |\n`;return out;
}

export function exportContributing(result:AnalysisResult):string{
  const candidates=result.rules.filter(r=>r.humanDecision?.action!=='ignore'&&!r.documented&&((r.humanDecision?.action==='promote'||r.humanDecision?.action==='override')||r.confidence>=65)&&r.status!=='stale');
  let out=`# CONTRIBUTING.md — ReviewDNA suggested additions\n\n> These are recurring review conventions that are not currently detected in repository documentation. Human review is required before adopting them.\n\n`;
  if(!candidates.length)return out+'No undocumented high-confidence conventions were found.\n';
  const byCategory=new Map<string,EngineeringRule[]>();
  for(const rule of candidates)byCategory.set(rule.category,[...(byCategory.get(rule.category)??[]),rule]);
  for(const [category,rules] of byCategory){
    out+=`## ${category}\n\n`;
    for(const rule of rules)out+=`- ${rule.text} _(${rule.confidence}% confidence; ${rule.evidenceCount} pieces of evidence; fingerprint: ${rule.fingerprint})_\n`;
    out+='\n';
  }
  return out;
}

export function exportDeltaMarkdown(delta:{newRules:EngineeringRule[];removedRules:EngineeringRule[];strengthened:Array<{before:EngineeringRule;after:EngineeringRule}>;weakened:Array<{before:EngineeringRule;after:EngineeringRule}>;changed?:Array<{before:EngineeringRule;after:EngineeringRule;changes:string[]}>;documentationChanges?:Array<{before:EngineeringRule;after:EngineeringRule;changes:string[]}>},repository:string):string{
  const changed=delta.changed??[],documentationChanges=delta.documentationChanges??[];
  let out=`# ${repository} ReviewDNA change report\n\n`;
  out+=`- New rules: ${delta.newRules.length}\n- Removed rules: ${delta.removedRules.length}\n- Strengthened: ${delta.strengthened.length}\n- Weakened: ${delta.weakened.length}\n- Changed: ${changed.length}\n- Documentation changes: ${documentationChanges.length}\n\n`;
  const section=(title:string,lines:string[])=>{if(lines.length)out+=`## ${title}\n\n${lines.map(x=>`- ${x}`).join('\n')}\n\n`;};
  section('New conventions',delta.newRules.map(r=>`[${r.category}] ${r.text} (${r.confidence}%)`));
  section('Removed conventions',delta.removedRules.map(r=>`[${r.category}] ${r.text}`));
  section('Strengthened',delta.strengthened.map(p=>`${p.after.text} (${p.before.confidence}% → ${p.after.confidence}%)`));
  section('Weakened',delta.weakened.map(p=>`${p.after.text} (${p.before.confidence}% → ${p.after.confidence}%)`));
  section('Convention changes',changed.map(p=>`${p.after.text} — ${p.changes.join(', ')}`));
  section('Documentation changes',documentationChanges.map(p=>`${p.after.text} — ${p.changes.join(', ')}`));
  return out;
}

export function buildKnowledgeProposalManifest(result:AnalysisResult):KnowledgeProposalManifest {
  const rules=selectPolicyRules(result).map(rule=>({
    fingerprint:rule.fingerprint,
    text:rule.text,
    category:rule.category,
    confidence:rule.confidence,
    evidenceCount:rule.evidenceCount,
    scope:[...rule.scope],
    ...(rule.humanDecision?{humanDecision:{...rule.humanDecision}}:{}),
    evidence:rule.evidence.map(evidence=>({
      prNumber:evidence.prNumber,
      reviewer:evidence.reviewer,
      createdAt:evidence.createdAt,
      url:evidence.url,
      ...(evidence.path!==undefined?{path:evidence.path}:{})
    }))
  }));
  return {
    version:1,
    repository:result.summary.repository,
    generatedAt:new Date().toISOString(),
    sourceAnalysisGeneratedAt:result.summary.generatedAt,
    rules,
    counts:{
      includedRules:rules.length,
      promotedRules:rules.filter(rule=>rule.humanDecision?.action==='promote').length,
      overriddenRules:rules.filter(rule=>rule.humanDecision?.action==='override').length,
      evidenceLinks:rules.reduce((sum,rule)=>sum+rule.evidence.length,0)
    }
  };
}

export function exportKnowledgeProposal(result:AnalysisResult):string {
  const manifest=buildKnowledgeProposalManifest(result);
  let out=`# ReviewDNA Knowledge Proposal\n\n`;
  out+=`Repository: **${manifest.repository}**  \nSource analysis: ${manifest.sourceAnalysisGeneratedAt}  \nIncluded conventions: ${manifest.counts.includedRules}  \nEvidence links: ${manifest.counts.evidenceLinks}\n\n`;
  out+=`> This package is a proposal, not an automatic policy update. Review the evidence and diff the proposed files before merging anything.\n\n`;
  for(const rule of manifest.rules){
    out+=`## ${rule.text}\n\n`;
    out+=`- Fingerprint: \`${rule.fingerprint}\`\n- Category: ${rule.category}\n- Confidence: ${rule.confidence}%\n- Evidence: ${rule.evidenceCount}\n- Scope: ${rule.scope.join(', ')}\n- Human decision: ${rule.humanDecision?.action??'automatic threshold'}\n\n`;
    for(const evidence of rule.evidence.slice(0,10))out+=`  - [PR #${evidence.prNumber}](${evidence.url}) — ${evidence.reviewer}, ${evidence.createdAt}${evidence.path?` — \`${evidence.path}\``:''}\n`;
    if(rule.evidence.length>10)out+=`  - …and ${rule.evidence.length-10} more evidence records in \`reviewdna-proposal.json\`.\n`;
    out+='\n';
  }
  return out;
}
